### ISSUE TITLE
Comparison with the graphql-query-compress compression approach

### ISSUE THREAD

**Issue by jaydenseric** [frontendr/babel-plugin-transform-compress-graphql#2]
This library appears to have a simple compression function based on string `replace()` and regex:

https://github.com/frontendr/babel-plugin-transform-compress-graphql/blob/1.1.0/src/index.js#L3

[`graphql-query-compress`](https://github.com/rse/graphql-query-compress) has a more complicated approach using lexical analysis:

https://github.com/rse/graphql-query-compress/blob/1.2.1/src/graphql-query-compress.js#L29

It is also heavier tho, with a [143kb install size](https://packagephobia.now.sh/result?p=graphql-query-compress).

Which approach is "safer"? If `graphql-query-compress` is "safer", does it make sense to use it in `babel-plugin-transform-compress-graphql`?

**Comment by frontendr** [comment]
Hi Jayden,

When I started with compressing my GraphQL queries I did that in the browser. I didn't want a huge library like that because that would defy the purpose. But then I wanted to make my bundles smaller also so I simply copied the function and created a Babel plugin around it.

I do agree with you that using `graphql-query-compress` would be safer and probably yield better results because the regular expression sometimes loses compression when queries are formatted differently. Also because it's a babel plugin it shouldn't have any effect on the resulting bundle size, only the build time.

I also like the idea that smarter people are testing the compression part of the plugin which removes a concern for me.

I'll have a look at integrating this package later this week.

**Comment by frontendr** [comment]
Replaced the `compress` function with that from `graphql-query-compress`. It's more concise than the regular expressions I used. The compression of the examples is about the same but now there are no more mixed spaces and commas in the queries.

I'll release it with `1.2.0` later this evening.

Thanks to @jaydenseric for the suggestion!
